config/routes.rb
RubyishResume::Application.routes.draw do

  resources :needs_quals

  resources :profsocieties

  resources :bibliographies

  resources :edus

  resources :experiencedetails

  resources :summaries

  resources :contactinfos

  match '/' => 'needs_quals#index'

end

app/models/profsociety.rb
class Profsociety < ActiveRecord::Base
  attr_accessible :socname
end

app/controllers/profsocieties_controller.rb
class ProfsocietiesController < ApplicationController
  # GET /profsocieties
  # GET /profsocieties.json
  def index
    @profsocieties = Profsociety.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profsocieties }
    end
  end

  # GET /profsocieties/1
  # GET /profsocieties/1.json
  def show
    @profsociety = Profsociety.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profsociety }
    end
  end

  # GET /profsocieties/new
  # GET /profsocieties/new.json
  def new
    @profsociety = Profsociety.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profsociety }
    end
  end

  # GET /profsocieties/1/edit
  def edit
    @profsociety = Profsociety.find(params[:id])
  end

  # POST /profsocieties
  # POST /profsocieties.json
  def create
    @profsociety = Profsociety.new(params[:profsociety])

    respond_to do |format|
      if @profsociety.save
        format.html { redirect_to @profsociety, notice: 'Profsociety was successfully created.' }
        format.json { render json: @profsociety, status: :created, location: @profsociety }
      else
        format.html { render action: "new" }
        format.json { render json: @profsociety.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profsocieties/1
  # PUT /profsocieties/1.json
  def update
    @profsociety = Profsociety.find(params[:id])

    respond_to do |format|
      if @profsociety.update_attributes(params[:profsociety])
        format.html { redirect_to @profsociety, notice: 'Profsociety was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profsociety.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profsocieties/1
  # DELETE /profsocieties/1.json
  def destroy
    @profsociety = Profsociety.find(params[:id])
    @profsociety.destroy

    respond_to do |format|
      format.html { redirect_to profsocieties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profsocieties_helper.rb
module ProfsocietiesHelper
end

app/views/profsocieties/_form.html.erb
<%= form_for(@profsociety) do |f| %>
  <% if @profsociety.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profsociety.errors.count, "error") %> prohibited this profsociety from being saved:</h2>

      <ul>
      <% @profsociety.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :socname %><br />
    <%= f.text_field :socname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profsocieties/edit.html.erb
<h1>Editing profsociety</h1>

<%= render 'form' %>

<%= link_to 'Show', @profsociety %> |
<%= link_to 'Back', profsocieties_path %>

app/views/profsocieties/index.html.erb
<h1>Mark McWiggins' Professional Society Affiliations</h1>

<table>
  <tr>
    <th>Society Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profsocieties.each do |profsociety| %>
  <tr>
    <td><%= profsociety.socname %></td>
    <td><%= link_to 'Show', profsociety %></td>
    <td><%= link_to 'Edit', edit_profsociety_path(profsociety) %></td>
    <td><%= link_to 'Destroy', profsociety, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profsociety', new_profsociety_path %><br />
<hr>
<table>
<tr><td><%= link_to 'Page 1', needs_quals_path %></td>
<td><%= link_to 'Education', edus_path %></td>
<td><%= link_to 'Contact', contactinfos_path %></td>
<td><%= link_to 'Summary', summaries_path %></td>
<td><%= link_to 'Experience', experiencedetails_path %></td>
<td><%= link_to 'Bibliography',bibliographies_path %></td>
<td><%= link_to 'Professional Societies',profsocieties_path %></td>
</tr>
</table>

app/views/profsocieties/new.html.erb
<h1>New profsociety</h1>

<%= render 'form' %>

<%= link_to 'Back', profsocieties_path %>

app/views/profsocieties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Socname:</b>
  <%= @profsociety.socname %>
</p>


<%= link_to 'Edit', edit_profsociety_path(@profsociety) %> |
<%= link_to 'Back', profsocieties_path %>