config/routes.rb
RubyishResume::Application.routes.draw do

  resources :needs_quals

  resources :profsocieties

  resources :bibliographies

  resources :edus

  resources :experiencedetails

  resources :summaries

  resources :contactinfos

  match '/' => 'needs_quals#index'

end

app/models/edu.rb
class Edu < ActiveRecord::Base
  attr_accessible :description, :kind
end

app/controllers/edus_controller.rb
class EdusController < ApplicationController
  # GET /edus
  # GET /edus.json
  def index
    @edus = Edu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @edus }
    end
  end

  # GET /edus/1
  # GET /edus/1.json
  def show
    @edu = Edu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edu }
    end
  end

  # GET /edus/new
  # GET /edus/new.json
  def new
    @edu = Edu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edu }
    end
  end

  # GET /edus/1/edit
  def edit
    @edu = Edu.find(params[:id])
  end

  # POST /edus
  # POST /edus.json
  def create
    @edu = Edu.new(params[:edu])

    respond_to do |format|
      if @edu.save
        format.html { redirect_to @edu, notice: 'Edu was successfully created.' }
        format.json { render json: @edu, status: :created, location: @edu }
      else
        format.html { render action: "new" }
        format.json { render json: @edu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /edus/1
  # PUT /edus/1.json
  def update
    @edu = Edu.find(params[:id])

    respond_to do |format|
      if @edu.update_attributes(params[:edu])
        format.html { redirect_to @edu, notice: 'Edu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @edu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edus/1
  # DELETE /edus/1.json
  def destroy
    @edu = Edu.find(params[:id])
    @edu.destroy

    respond_to do |format|
      format.html { redirect_to edus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/edus_helper.rb
module EdusHelper
end

app/views/edus/_form.html.erb
<%= form_for(@edu) do |f| %>
  <% if @edu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edu.errors.count, "error") %> prohibited this edu from being saved:</h2>

      <ul>
      <% @edu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/edus/edit.html.erb
<h1>Editing edu</h1>

<%= render 'form' %>

<%= link_to 'Show', @edu %> |
<%= link_to 'Back', edus_path %>

app/views/edus/index.html.erb
<h1>Mark McWiggins' Education</h1>

<table>
  <tr>
    <th>Kind</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @edus.each do |edu| %>
  <tr>
    <td><%= edu.kind %></td>
    <td><%= edu.description %></td>
    <td><%= link_to 'Show', edu %></td>
    <td><%= link_to 'Edit', edit_edu_path(edu) %></td>
    <td><%= link_to 'Destroy', edu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edu', new_edu_path %>
<hr>
<table>
<tr><td><%= link_to 'Page 1', needs_quals_path %></td>
<td><%= link_to 'Education', edus_path %></td>
<td><%= link_to 'Contact', contactinfos_path %></td>
<td><%= link_to 'Summary', summaries_path %></td>
<td><%= link_to 'Experience', experiencedetails_path %></td>
<td><%= link_to 'Bibliography',bibliographies_path %></td>
<td><%= link_to 'Professional Societies',profsocieties_path %></td>
</tr>
</table>

app/views/edus/new.html.erb
<h1>New edu</h1>

<%= render 'form' %>

<%= link_to 'Back', edus_path %>

app/views/edus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kind:</b>
  <%= @edu.kind %>
</p>

<p>
  <b>Description:</b>
  <%= @edu.description %>
</p>


<%= link_to 'Edit', edit_edu_path(@edu) %> |
<%= link_to 'Back', edus_path %>