config/routes.rb
RubyishResume::Application.routes.draw do

  resources :needs_quals

  resources :profsocieties

  resources :bibliographies

  resources :edus

  resources :experiencedetails

  resources :summaries

  resources :contactinfos

  match '/' => 'needs_quals#index'

end

app/models/needs_qual.rb
class NeedsQual < ActiveRecord::Base
  attr_accessible :myquals, :yourneeds
end

app/controllers/needs_quals_controller.rb
class NeedsQualsController < ApplicationController
  # GET /needs_quals
  # GET /needs_quals.json
  def index
    @needs_quals = NeedsQual.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @needs_quals }
    end
  end

  # GET /needs_quals/1
  # GET /needs_quals/1.json
  def show
    @needs_qual = NeedsQual.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @needs_qual }
    end
  end

  # GET /needs_quals/new
  # GET /needs_quals/new.json
  def new
    @needs_qual = NeedsQual.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @needs_qual }
    end
  end

  # GET /needs_quals/1/edit
  def edit
    @needs_qual = NeedsQual.find(params[:id])
  end

  # POST /needs_quals
  # POST /needs_quals.json
  def create
    @needs_qual = NeedsQual.new(params[:needs_qual])

    respond_to do |format|
      if @needs_qual.save
        format.html { redirect_to @needs_qual, notice: 'Needs qual was successfully created.' }
        format.json { render json: @needs_qual, status: :created, location: @needs_qual }
      else
        format.html { render action: "new" }
        format.json { render json: @needs_qual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /needs_quals/1
  # PUT /needs_quals/1.json
  def update
    @needs_qual = NeedsQual.find(params[:id])

    respond_to do |format|
      if @needs_qual.update_attributes(params[:needs_qual])
        format.html { redirect_to @needs_qual, notice: 'Needs qual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @needs_qual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs_quals/1
  # DELETE /needs_quals/1.json
  def destroy
    @needs_qual = NeedsQual.find(params[:id])
    @needs_qual.destroy

    respond_to do |format|
      format.html { redirect_to needs_quals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/needs_quals_helper.rb
module NeedsQualsHelper
end

app/views/needs_quals/_form.html.erb
<%= form_for(@needs_qual) do |f| %>
  <% if @needs_qual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@needs_qual.errors.count, "error") %> prohibited this needs_qual from being saved:</h2>

      <ul>
      <% @needs_qual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :yourneeds %><br />
    <%= f.text_area :yourneeds %>
  </div>
  <div class="field">
    <%= f.label :myquals %><br />
    <%= f.text_area :myquals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needs_quals/edit.html.erb
<h1>Editing needs_qual</h1>

<%= render 'form' %>

<%= link_to 'Show', @needs_qual %> |
<%= link_to 'Back', needs_quals_path %>

app/views/needs_quals/index.html.erb
<h1>Mark McWiggins' Resume: Page 1</h1>

<table>
  <tr>
    <th>Your Needs</th>
    <th>My Qualifications</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @needs_quals.each do |needs_qual| %>
  <tr>
    <td><%= needs_qual.yourneeds %></td>
    <td><%= needs_qual.myquals %></td>
    <td><%= link_to 'Show', needs_qual %></td>
    <td><%= link_to 'Edit', edit_needs_qual_path(needs_qual) %></td>
    <td><%= link_to 'Destroy', needs_qual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Needs qual', new_needs_qual_path %>
<hr>
<table>
<tr><td><%= link_to 'Page 1', needs_quals_path %></td>
<td><%= link_to 'Education', edus_path %></td>
<td><%= link_to 'Contact', contactinfos_path %></td>
<td><%= link_to 'Summary', summaries_path %></td>
<td><%= link_to 'Experience', experiencedetails_path %></td>
<td><%= link_to 'Bibliography',bibliographies_path %></td>
<td><%= link_to 'Professional Societies',profsocieties_path %></td>
</tr>
</table>

app/views/needs_quals/new.html.erb
<h1>New needs_qual</h1>

<%= render 'form' %>

<%= link_to 'Back', needs_quals_path %>

app/views/needs_quals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Yourneeds:</b>
  <%= @needs_qual.yourneeds %>
</p>

<p>
  <b>Myquals:</b>
  <%= @needs_qual.myquals %>
</p>


<%= link_to 'Edit', edit_needs_qual_path(@needs_qual) %> |
<%= link_to 'Back', needs_quals_path %>