config/routes.rb
RubyishResume::Application.routes.draw do

  resources :needs_quals

  resources :profsocieties

  resources :bibliographies

  resources :edus

  resources :experiencedetails

  resources :summaries

  resources :contactinfos

  match '/' => 'needs_quals#index'

end

app/models/bibliography.rb
class Bibliography < ActiveRecord::Base
  attr_accessible :author_or_url, :title
end

app/controllers/bibliographies_controller.rb
class BibliographiesController < ApplicationController
  # GET /bibliographies
  # GET /bibliographies.json
  def index
    @bibliographies = Bibliography.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bibliographies }
    end
  end

  # GET /bibliographies/1
  # GET /bibliographies/1.json
  def show
    @bibliography = Bibliography.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bibliography }
    end
  end

  # GET /bibliographies/new
  # GET /bibliographies/new.json
  def new
    @bibliography = Bibliography.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bibliography }
    end
  end

  # GET /bibliographies/1/edit
  def edit
    @bibliography = Bibliography.find(params[:id])
  end

  # POST /bibliographies
  # POST /bibliographies.json
  def create
    @bibliography = Bibliography.new(params[:bibliography])

    respond_to do |format|
      if @bibliography.save
        format.html { redirect_to @bibliography, notice: 'Bibliography was successfully created.' }
        format.json { render json: @bibliography, status: :created, location: @bibliography }
      else
        format.html { render action: "new" }
        format.json { render json: @bibliography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bibliographies/1
  # PUT /bibliographies/1.json
  def update
    @bibliography = Bibliography.find(params[:id])

    respond_to do |format|
      if @bibliography.update_attributes(params[:bibliography])
        format.html { redirect_to @bibliography, notice: 'Bibliography was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bibliography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bibliographies/1
  # DELETE /bibliographies/1.json
  def destroy
    @bibliography = Bibliography.find(params[:id])
    @bibliography.destroy

    respond_to do |format|
      format.html { redirect_to bibliographies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bibliographies_helper.rb
module BibliographiesHelper
end

app/views/bibliographies/_form.html.erb
<%= form_for(@bibliography) do |f| %>
  <% if @bibliography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bibliography.errors.count, "error") %> prohibited this bibliography from being saved:</h2>

      <ul>
      <% @bibliography.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author_or_url %><br />
    <%= f.text_field :author_or_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bibliographies/edit.html.erb
<h1>Editing bibliography</h1>

<%= render 'form' %>

<%= link_to 'Show', @bibliography %> |
<%= link_to 'Back', bibliographies_path %>

app/views/bibliographies/index.html.erb
<h1>Relevant Bibliography for this Position</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author or url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bibliographies.each do |bibliography| %>
  <tr>
    <td><%= bibliography.title %></td>
    <td><%= bibliography.author_or_url %></td>
    <td><%= link_to 'Show', bibliography %></td>
    <td><%= link_to 'Edit', edit_bibliography_path(bibliography) %></td>
    <td><%= link_to 'Destroy', bibliography, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bibliography', new_bibliography_path %>
<hr>
<table>
<tr><td><%= link_to 'Page 1', needs_quals_path %></td>
<td><%= link_to 'Education', edus_path %></td>
<td><%= link_to 'Contact', contactinfos_path %></td>
<td><%= link_to 'Summary', summaries_path %></td>
<td><%= link_to 'Experience', experiencedetails_path %></td>
<td><%= link_to 'Bibliography',bibliographies_path %></td>
<td><%= link_to 'Professional Societies',profsocieties_path %></td>
</tr>
</table>

app/views/bibliographies/new.html.erb
<h1>New bibliography</h1>

<%= render 'form' %>

<%= link_to 'Back', bibliographies_path %>

app/views/bibliographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bibliography.title %>
</p>

<p>
  <b>Author or url:</b>
  <%= @bibliography.author_or_url %>
</p>


<%= link_to 'Edit', edit_bibliography_path(@bibliography) %> |
<%= link_to 'Back', bibliographies_path %>